### ISSUE TITLE
Searching AUR points to unexpected db

### ISSUE THREAD

**Issue by fhdk** [manjaro/pamac-cli#1]
## Version
```
 $ pamac --version
pamac-cli 11.6.0  -  libpamac 11.7.0
Copyright © 2019-2024 Guillaume Benoit
This program is free software, you can redistribute it under the terms of the GNU GPL.
```
## Reproduce
```
 $ pamac search j4335dw --aur
Failed to read AUR data from /var/lib/pacman/sync/packages-meta-ext-v1.json.gz : Error opening file /var/lib/pacman/sync/packages-meta-ext-v1.json.gz: No such file or directory
```

## Expected result

https://aur.archlinux.org/packages?K=j4335dw

As pamac runs with user permissions - the dbs are stored in
```
/var/tmp/pamac/dbs
```

**Comment by philmmanjaro** [comment]
Did you do a `pamac upgrade --aur` first? On my end it works after that:

```
pamac search j4335dw --aur
brother-mfc-j4335dw  3.5.0-1                                                 AUR
    LPR driver and CUPS wrapper for Brother MFC-J4335DW printer
```

**Comment by fhdk** [comment]
I never use `pamac upgrade --aur`.

But I did try the **Refresh databases** in the GUI - which did not change anything.

**Comment by philmmanjaro** [comment]
there is: `pamac upgrade --aur --force-refresh`

**Comment by fhdk** [comment]
I don't think you understand what I mean.

The **upgrade** requires superuser authentication - I don't want to upgrade.

And authentication should not be necessary to fetch aur database which is not necessary for other databases as those are downloaded to a writable location.

The problem is the location pamac looks for the aur metadata - `/var/lib/pacman/sync` which is not the location pamac should look in - the correct location is `/var/tmp/pamac/dbs`.

**Comment by philmmanjaro** [comment]
With **libalpm v15** it looks in sync folder as committed here: https://github.com/manjaro/libpamac/commit/58b6781ea0020e78c668f286a9017ad663ae6fba#diff-89f8f593e2131efdb6afab6b6fb62c5e69ae27f41d0178ae271539f6d39a31fdR329. So call `pamac upgrade --aur` once to get the needed databases. After that you can search for files. There is no need to go thru with the upgrade.  You can also do a `--dry-run`. more options explained here: `pamac upgrade --help`

**Comment by philmmanjaro** [comment]
See here for the AUR database:

```
ls -l /var/lib/pacman/sync
total 64448
-rw-r--r-- 1 root root   144854 00:10 27 Thg 10 core.db
-rw-r--r-- 1 root root  2696311 00:10 27 Thg 10 core.files
-rw-r--r-- 1 root root  8485923 01:08 27 Thg 10 extra.db
-rw-r--r-- 1 root root 43283446 01:08 27 Thg 10 extra.files
-rw-r--r-- 1 root root   144856 00:13 27 Thg 10 multilib.db
-rw-r--r-- 1 root root   238543 00:13 27 Thg 10 multilib.files
-rw-r--r-- 1 root root 10983841 09:24 23 Thg 10 packages-meta-ext-v1.json.gz
-rw-r--r-- 1 root root        0 13:55 27 Thg 10 refresh_timestamp
```

**Comment by philmmanjaro** [comment]
Also for `pacman` you need authorization to fetch databases:

```
pacman -Syy
error: you cannot perform this operation unless you are root.
```

**Comment by philmmanjaro** [comment]
Here for just the files:

```
pacman -Fyy
error: you cannot perform this operation unless you are root
```

**Comment by guinux** [comment]
Yes, with libalpm 15 support, AUR database location moved to /var/lib/pacman/sync. If you try to Refresh databases from the GUI, it should work.

**Comment by philmmanjaro** [comment]
@72757373656c6c did you called `pamac upgrade --aur` as I noted before? That is the similar cmd as doing it via UI in `pamac-manager`.

**Comment by philmmanjaro** [comment]
There was no proper transition from the old way we handled AUR support before libalpm v15. On a new system you may not have this issue at all. @guinux might check again if there are any differences and why the search function errors out when the database is not found. I think when it is not given either try to fetch the database automatically or tell the user to update all databases with `pamac upgrade --aur --force-refresh --dry-run`.
